baseURL = 'https://vibrantifix.github.io/'
languageCode = 'en-us'
title = 'Vibrantifix'
theme = 'congo'

[author]
  name = "Yogesh"
  image = "img/author.jpg"
  headline = "I hope you will find what you're looking for ---<--{(@"
  bio = "I hope you will find what you're looking for ---<--{(@"
  links = [
    { github = "https://github.com/vibrantifix" },
    { link = "https://vibrantifix.github.io/" },
    { gitlab = "https://gitlab.com/" },
    { telegram = "https://telegram.com/" },
  ]